### PR TITLE
Support Ecto 3.0

### PR DESCRIPTION
**Pull request by mcrumm**
The latest Ecto update [splits the repository apart](https://github.com/elixir-ecto/ecto/blob/master/CHANGELOG.md#split-ecto-into-ecto-and-ecto_sql), so to support both versions, we need to add both `:ecto` and `:ecto_sql` as optional dependencies.

### CODE REVIEW

**Comment by mcrumm** [comment]
@bryanjos I realize there are still some additional changes that need made here, but this may also be held up until the next ecto release: https://github.com/elixir-ecto/ecto/pull/2798

**Comment by bryanjos** [comment]
@mcrumm sorry for the delay and thanks! I'll take a look today to get this up to ecto 3.0

**Comment by bryanjos** [comment]
Thanks again for the PR! I updated the lib to use ecto 3.0 and updated it to 1.0!

**Comment by mcrumm** [comment]
Sorry for leaving this hanging, and thanks for the update!

**Pull request closed without merging**
